namespace LingoIsland.Video;

/// <summary>
/// 影片字幕取得（[techItem字幕擷取]，spec#2）：抽介面供測試以假實作注入、不打真網路／不起 CLI；
/// 正式實作見 <see cref="YtDlpSubtitleFetcher"/>。**僅取字幕文字、不下載影片內容。**
/// </summary>
public interface ISubtitleFetcher
{
    /// <summary>取指定 YouTube 影片之英文字幕逐句 cue（優先人工字幕、退自動字幕）；無字幕／取得失敗擲 <see cref="SubtitleException"/>。</summary>
    Task<SubtitleFetchResult> FetchAsync(string videoUrlOrId, CancellationToken ct = default);

    /// <summary>取**指定軌別**字幕（Row1 手動切換基底，#189）：<paramref name="wantAuto"/>＝false 只取人工、true 只取自動；該軌不存在擲 <see cref="SubtitleException"/>。</summary>
    Task<SubtitleFetchResult> FetchTrackAsync(string videoUrlOrId, bool wantAuto, CancellationToken ct = default);

    /// <summary>
    /// 探測影片內嵌英文字幕可用性（#177 搜尋結果表格「內嵌字幕」欄）：只查 yt-dlp metadata
    /// （<c>subtitles</c>／<c>automatic_captions</c>），<b>不下載字幕內容、不下載影片</b>，故較 <see cref="FetchAsync"/> 輕快。
    /// 私人／移除／逾時等取得失敗擲 <see cref="SubtitleException"/>，由 UI 逐列容錯（該列顯示「無法確認」、不影響他列）。
    /// </summary>
    Task<EmbeddedSubtitleInfo> ProbeEmbeddedAsync(string videoUrlOrId, CancellationToken ct = default);
}

/// <summary>
/// 影片內嵌英文字幕可用性（[techItem字幕擷取] 延伸，#177）：<see cref="HasManual"/> 人工（真人上傳、句級乾淨、最佳學習素材）、
/// <see cref="HasAuto"/> 自動（YouTube 機器轉錄／自動翻譯）。皆 false＝查無英文字幕。僅為挑片提示、非保證（實際以載入時抓取為準）。
/// </summary>
public sealed record EmbeddedSubtitleInfo(bool HasManual, bool HasAuto);

/// <summary>
/// 字幕取得結果（[techItem字幕擷取]，spec#2）：逐句 <see cref="SubtitleCue"/> ＋來源是否為
/// <see cref="IsAutoGenerated"/> 自動生成字幕（逐字滾動、較不精準——UI 據此提示使用者「本片僅自動字幕、學習體驗較差」）。
/// </summary>
public sealed record SubtitleFetchResult(IReadOnlyList<SubtitleCue> Cues, bool IsAutoGenerated);

/// <summary>字幕取得之明確可讀失敗（無字幕、yt-dlp 缺失、私人／無效影片、逾時等）——中止該片、不當機不無聲失敗。</summary>
public sealed class SubtitleException : Exception
{
    public SubtitleException(string message) : base(message) { }
}
