using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace LingoIsland.Video;

/// <summary>一支影片之已載入字幕（#174；#189 改資料夾式）：逐句 cue（含說話人／YAML 編修／AI 推斷）＋來源是否自動生成＋標題＋存檔時間。以 VideoId 為鍵。</summary>
public sealed class SavedSubtitle
{
    public string VideoId { get; set; } = "";
    public string Title { get; set; } = "";
    public bool IsAutoGenerated { get; set; }
    public List<SubtitleCue> Cues { get; set; } = new();
    public string SavedAt { get; set; } = ""; // ISO 8601
}

/// <summary>一支影片資料夾之 <c>info.json</c> 中繼（#189）：逐句在同資料夾 <c>subtitle.yaml</c>、逐字稿原文為 <c>{yyyyMMdd} {來源}.txt</c>。</summary>
public sealed class VideoInfo
{
    public string VideoId { get; set; } = "";
    public string Title { get; set; } = "";
    public bool IsAutoGenerated { get; set; }
    public string FirstLoadAt { get; set; } = ""; // ISO 8601；資料夾日期碼取此
    public string SavedAt { get; set; } = "";      // ISO 8601；最後存檔
}

/// <summary>
/// 影片字幕本機儲存（[modVideoCapture模組]，#174；#189 重構為**每支影片一資料夾**）：
/// 根目錄 <c>%APPDATA%\LingoIsland\video</c>，每支影片一資料夾、名為 <c>{yyyyMMdd 初次載入} {影片標題}</c>；
/// 內含 <c>subtitle.yaml</c>（逐句字幕，YAML）、<c>info.json</c>（中繼）、以及 🌐 Script 抓到的 <c>{yyyyMMdd} {來源網站}.txt</c>（逐字稿原文，可多份）。
/// videoId→資料夾以掃描 <c>info.json</c> 建索引（記憶體快取）。舊版扁平 <c>subtitles\{id}.json</c> 由 <see cref="MigrateLegacy"/> 一次性搬遷。讀寫失敗降級不致命。
/// </summary>
public sealed class SubtitleStore
{
    private static readonly JsonSerializerOptions Opts = new() { WriteIndented = true };
    private readonly string _root;
    private Dictionary<string, string>? _index; // videoId → 資料夾完整路徑（掃 info.json 建、建新夾時更新）

    private const string SubtitleFile = "subtitle.yaml";
    private const string InfoFile = "info.json";

    public SubtitleStore(string? root = null) { _root = root ?? DefaultRoot; }

    /// <summary>字幕資料夾根（#189）：<c>%APPDATA%\LingoIsland\video</c>。各影片子資料夾即在其下。</summary>
    public static string DefaultRoot => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "LingoIsland", "video");

    private string LegacyDir => Path.Combine(Directory.GetParent(_root)!.FullName, "subtitles"); // 舊版扁平存放

    // ── 索引（videoId → 資料夾） ──

    private Dictionary<string, string> Index()
    {
        if (_index is not null) { return _index; }
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        try
        {
            if (Directory.Exists(_root))
            {
                foreach (var dir in Directory.EnumerateDirectories(_root))
                {
                    try
                    {
                        var infoPath = Path.Combine(dir, InfoFile);
                        if (!File.Exists(infoPath)) { continue; }
                        var info = JsonSerializer.Deserialize<VideoInfo>(File.ReadAllText(infoPath));
                        if (info is not null && !string.IsNullOrEmpty(info.VideoId)) { map[info.VideoId] = dir; }
                    }
                    catch { /* 略過壞資料夾 */ }
                }
            }
        }
        catch { /* 掃描失敗→空索引 */ }
        _index = map;
        return map;
    }

    /// <summary>取某影片之資料夾路徑；未存在回 null（不建立）。</summary>
    private string? FolderOf(string videoId) => Index().TryGetValue(videoId, out var d) ? d : null;

    /// <summary>建立某影片之資料夾（名＝<c>{firstLoad:yyyyMMdd} {標題}</c>；同名不同片→加序號）；更新索引、回路徑。</summary>
    private string CreateFolder(string videoId, string? title, DateTimeOffset firstLoad)
    {
        Directory.CreateDirectory(_root);
        var baseName = firstLoad.ToString("yyyyMMdd") + " " + SanitizeName(title);
        var name = baseName;
        for (var n = 2; Directory.Exists(Path.Combine(_root, name)) && !BelongsTo(Path.Combine(_root, name), videoId); n++)
        {
            name = baseName + " (" + n + ")"; // 撞名（同日同標題不同片）→加序號
        }
        var path = Path.Combine(_root, name);
        Directory.CreateDirectory(path);
        Index()[videoId] = path;
        return path;
    }

    private static bool BelongsTo(string dir, string videoId)
    {
        try
        {
            var info = JsonSerializer.Deserialize<VideoInfo>(File.ReadAllText(Path.Combine(dir, InfoFile)));
            return info?.VideoId == videoId;
        }
        catch { return false; }
    }

    // ── 存 / 讀 ──

    /// <summary>存一支影片之字幕（覆寫 subtitle.yaml＋info.json）；videoId 空、無有效鍵或 cues 空則略過。首次建立資料夾（日期＝現在＝初次載入）；再存保留 FirstLoadAt。</summary>
    public void Save(string videoId, string? title, bool isAutoGenerated, IReadOnlyList<SubtitleCue> cues)
    {
        if (string.IsNullOrWhiteSpace(videoId) || SanitizeKey(videoId).Length == 0 || cues is null || cues.Count == 0) { return; }
        try
        {
            var now = DateTimeOffset.Now;
            var folder = FolderOf(videoId);
            var firstLoad = now;
            if (folder is null) { folder = CreateFolder(videoId, title, now); }
            else
            {
                var prev = ReadInfo(folder);
                if (prev is not null && DateTimeOffset.TryParse(prev.FirstLoadAt, out var f)) { firstLoad = f; } // 保留初次載入日
            }
            File.WriteAllText(Path.Combine(folder, SubtitleFile), SubtitleYaml.Serialize(cues));
            WriteInfo(folder, new VideoInfo
            {
                VideoId = videoId,
                Title = title ?? "",
                IsAutoGenerated = isAutoGenerated,
                FirstLoadAt = firstLoad.ToString("o"),
                SavedAt = now.ToString("o"),
            });
        }
        catch { /* 寫入失敗不影響主流程 */ }
    }

    /// <summary>存/更新一支影片之**網路逐字稿原文**（#189，🌐 Script 取得後）：寫入該片資料夾 <c>{yyyyMMdd} {來源}.txt</c>（同日同源覆寫、可多份）；transcript 空白略過。</summary>
    public void SaveWebTranscript(string videoId, string? title, string? transcript, string? source)
    {
        if (string.IsNullOrWhiteSpace(videoId) || SanitizeKey(videoId).Length == 0 || string.IsNullOrWhiteSpace(transcript)) { return; }
        try
        {
            var folder = FolderOf(videoId) ?? CreateFolder(videoId, title, DateTimeOffset.Now);
            var name = DateTimeOffset.Now.ToString("yyyyMMdd") + " " + SanitizeName(string.IsNullOrWhiteSpace(source) ? "transcript" : source) + ".txt";
            File.WriteAllText(Path.Combine(folder, name), transcript);
        }
        catch { /* 不致命 */ }
    }

    /// <summary>讀一支影片之已存字幕（info.json＋subtitle.yaml）；無則退舊版扁平檔（#189 相容）；皆無／空／解析失敗回 null。</summary>
    public SavedSubtitle? TryLoad(string videoId)
    {
        if (string.IsNullOrWhiteSpace(videoId)) { return null; }
        try
        {
            var folder = FolderOf(videoId);
            if (folder is not null)
            {
                var info = ReadInfo(folder);
                var yamlPath = Path.Combine(folder, SubtitleFile);
                if (info is not null && File.Exists(yamlPath))
                {
                    var cues = SubtitleYaml.Parse(File.ReadAllText(yamlPath));
                    if (cues.Count > 0)
                    {
                        return new SavedSubtitle { VideoId = info.VideoId, Title = info.Title, IsAutoGenerated = info.IsAutoGenerated, Cues = cues.ToList(), SavedAt = info.SavedAt };
                    }
                }
            }
            return TryLoadLegacy(videoId); // 尚未搬遷者仍可載入（不致資料遺失）
        }
        catch { return null; }
    }

    /// <summary>刪一支影片之資料夾（該影片自清單移除時）＋舊版扁平檔。</summary>
    public void Remove(string videoId)
    {
        if (string.IsNullOrWhiteSpace(videoId)) { return; }
        try
        {
            var folder = FolderOf(videoId);
            if (folder is not null && Directory.Exists(folder)) { Directory.Delete(folder, recursive: true); }
            _index?.Remove(videoId);
            var legacy = LegacyPath(videoId);
            if (File.Exists(legacy)) { File.Delete(legacy); }
        }
        catch { /* 不致命 */ }
    }

    /// <summary>清空所有影片資料夾（Clear all videos 時）＋舊版扁平目錄。</summary>
    public void Clear()
    {
        try { if (Directory.Exists(_root)) { Directory.Delete(_root, recursive: true); } } catch { /* 盡力 */ }
        try { if (Directory.Exists(LegacyDir)) { Directory.Delete(LegacyDir, recursive: true); } } catch { /* 盡力 */ }
        _index = null;
    }

    /// <summary>取某影片之資料夾路徑供開啟（#189 開啟資料夾鈕）：不存在則以標題新建（空影片夾亦可，供後續存檔）；videoId 無效回 null。</summary>
    public string? FolderFor(string videoId, string? title)
    {
        if (string.IsNullOrWhiteSpace(videoId) || SanitizeKey(videoId).Length == 0) { return null; }
        try { return FolderOf(videoId) ?? CreateFolder(videoId, title, DateTimeOffset.Now); }
        catch { return null; }
    }

    // ── 舊版扁平檔（%APPDATA%\LingoIsland\subtitles\{id}.json）相容與搬遷 ──

    private string LegacyPath(string videoId) => Path.Combine(LegacyDir, SanitizeKey(videoId) + ".json");

    private SavedSubtitle? TryLoadLegacy(string videoId)
    {
        try
        {
            var path = LegacyPath(videoId);
            if (!File.Exists(path)) { return null; }
            var data = JsonSerializer.Deserialize<LegacySaved>(File.ReadAllText(path));
            return data is { Cues.Count: > 0 }
                ? new SavedSubtitle { VideoId = data.VideoId, Title = "", IsAutoGenerated = data.IsAutoGenerated, Cues = data.Cues, SavedAt = data.SavedAt }
                : null;
        }
        catch { return null; }
    }

    /// <summary>
    /// 一次性搬遷舊版扁平 <c>subtitles\{id}.json</c> → 新資料夾結構（#189）：標題／初次載入日取自 <paramref name="videos"/>（videoId→(Title, AddedAt)）；
    /// 有 WebTranscript 者一併寫成逐字稿 .txt。逐檔盡力（失敗略過），搬遷成功即刪舊檔；全數搬完刪空舊目錄。已存在新資料夾者略過。
    /// </summary>
    public void MigrateLegacy(IReadOnlyDictionary<string, (string Title, string AddedAt)> videos)
    {
        try
        {
            if (!Directory.Exists(LegacyDir)) { return; }
            foreach (var file in Directory.EnumerateFiles(LegacyDir, "*.json"))
            {
                try
                {
                    var data = JsonSerializer.Deserialize<LegacySaved>(File.ReadAllText(file));
                    var id = string.IsNullOrEmpty(data?.VideoId) ? Path.GetFileNameWithoutExtension(file) : data!.VideoId;
                    if (string.IsNullOrEmpty(id) || data is null || data.Cues.Count == 0) { File.Delete(file); continue; }
                    if (FolderOf(id) is not null) { File.Delete(file); continue; } // 已搬遷

                    videos.TryGetValue(id, out var meta);
                    var title = string.IsNullOrWhiteSpace(meta.Title) ? id : meta.Title;
                    var firstLoad = DateTimeOffset.TryParse(meta.AddedAt, out var a) ? a
                        : DateTimeOffset.TryParse(data.SavedAt, out var s) ? s : DateTimeOffset.Now;

                    var folder = CreateFolder(id, title, firstLoad);
                    File.WriteAllText(Path.Combine(folder, SubtitleFile), SubtitleYaml.Serialize(data.Cues));
                    WriteInfo(folder, new VideoInfo { VideoId = id, Title = title, IsAutoGenerated = data.IsAutoGenerated, FirstLoadAt = firstLoad.ToString("o"), SavedAt = string.IsNullOrEmpty(data.SavedAt) ? firstLoad.ToString("o") : data.SavedAt });
                    if (!string.IsNullOrWhiteSpace(data.WebTranscript))
                    {
                        var tName = firstLoad.ToString("yyyyMMdd") + " " + SanitizeName(string.IsNullOrWhiteSpace(data.WebTranscriptSource) ? "transcript" : data.WebTranscriptSource) + ".txt";
                        File.WriteAllText(Path.Combine(folder, tName), data.WebTranscript);
                    }
                    File.Delete(file);
                }
                catch { /* 該檔搬遷失敗→留著、下次再試 */ }
            }
            try { if (!Directory.EnumerateFileSystemEntries(LegacyDir).Any()) { Directory.Delete(LegacyDir); } } catch { /* 盡力 */ }
        }
        catch { /* 搬遷整體失敗不致命 */ }
    }

    // ── 內部工具 ──

    private static VideoInfo? ReadInfo(string folder)
    {
        try { return JsonSerializer.Deserialize<VideoInfo>(File.ReadAllText(Path.Combine(folder, InfoFile))); }
        catch { return null; }
    }

    private static void WriteInfo(string folder, VideoInfo info)
        => File.WriteAllText(Path.Combine(folder, InfoFile), JsonSerializer.Serialize(info, Opts));

    /// <summary>YouTube 影片 ID 僅含 [A-Za-z0-9_-]；防呆濾除其餘字元，避免以外來字串組出越界路徑（舊版檔名鍵用）。</summary>
    private static string SanitizeKey(string videoId) =>
        new string((videoId ?? "").Where(c => char.IsLetterOrDigit(c) || c is '_' or '-').ToArray());

    /// <summary>資料夾/檔名安全化：去除檔名非法字元、收合空白、截長；空→untitled。</summary>
    private static string SanitizeName(string? s)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var cleaned = new string((s ?? "").Select(c => invalid.Contains(c) ? ' ' : c).ToArray());
        cleaned = Regex.Replace(cleaned, @"\s+", " ").Trim().TrimEnd('.'); // 尾點在 Windows 資料夾名會被吞
        if (cleaned.Length > 80) { cleaned = cleaned[..80].Trim(); }
        return cleaned.Length == 0 ? "untitled" : cleaned;
    }

    /// <summary>舊版扁平存檔模型（僅供搬遷/相容讀取；含已停用之 WebTranscript 欄）。</summary>
    private sealed class LegacySaved
    {
        public string VideoId { get; set; } = "";
        public bool IsAutoGenerated { get; set; }
        public List<SubtitleCue> Cues { get; set; } = new();
        public string SavedAt { get; set; } = "";
        public string? WebTranscript { get; set; }
        public string? WebTranscriptSource { get; set; }
    }
}
