using System.Diagnostics;
using System.IO;
using System.Text.Json;

namespace LingoIsland.Video;

/// <summary>
/// 以本機 <c>yt-dlp</c> 取 YouTube 影片英文字幕（[techItem字幕擷取]／[modVideoCapture模組] 影片擷取契約，spec#2）：
/// <see cref="Process"/> 啟動、僅下載字幕檔（VTT）、以 <see cref="SubtitleParser"/> 解析為逐句 cue。
/// **兩趟策略**：先只取<b>人工（真人）字幕</b>（VTT、乾淨句級、最佳學習素材）；查無才退取<b>自動字幕</b>
/// （改取 <b>json3</b> 事件級格式——避開 YouTube 自動字幕 VTT 之逐字滾動渲染破碎；json3 乾淨無滾動，惟仍為機器轉錄或有誤），
/// 並於 <see cref="SubtitleFetchResult.IsAutoGenerated"/> 標記供 UI 提示。
/// 無字幕／yt-dlp 缺失／私人或無效影片／逾時／非零離開碼一律擲 <see cref="SubtitleException"/>（中止該片、不當機）。
/// **僅取字幕文字、不下載影片內容**（<c>--skip-download</c>）。
/// </summary>
public sealed class YtDlpSubtitleFetcher : ISubtitleFetcher
{
    private readonly string _ytDlpPath;
    private readonly int _timeoutSec;
    private const int ProbeTimeoutSec = 25; // 內嵌字幕探測（只查 metadata）用較短逾時，免整排搜尋結果卡住

    public YtDlpSubtitleFetcher(string ytDlpPath = "yt-dlp", int timeoutSec = 60)
    {
        _ytDlpPath = ytDlpPath;
        _timeoutSec = timeoutSec;
    }

    public async Task<SubtitleFetchResult> FetchAsync(string videoUrlOrId, CancellationToken ct = default)
    {
        var url = Validate(videoUrlOrId);
        var dir = MakeTempDir();
        try
        {
            // 第一趟：僅人工（真人）字幕（VTT、句級乾淨、到句暫停最佳）。查得即用、標記非自動。
            var manual = await FetchManualCuesAsync(url, dir, ct);
            if (manual is { Count: > 0 }) { return new SubtitleFetchResult(manual, IsAutoGenerated: false); }
            // 第二趟：無人工字幕→退自動字幕（json3 事件級、乾淨無滾動；仍為機器轉錄）。
            ClearSubs(dir);
            var auto = await FetchAutoCuesAsync(url, dir, ct);
            return new SubtitleFetchResult(auto, IsAutoGenerated: true);
        }
        finally
        {
            DeleteTempDir(dir);
        }
    }

    /// <summary>
    /// 取**指定軌別**字幕（Row1 手動切換基底來源，#189）：<paramref name="wantAuto"/>＝false 只取人工 VTT、true 只取自動 json3。
    /// 該軌不存在（或無可讀句）擲 <see cref="SubtitleException"/>——供 UI 還原切換前狀態並提示。與 <see cref="FetchAsync"/> 共用兩趟解析邏輯。
    /// </summary>
    public async Task<SubtitleFetchResult> FetchTrackAsync(string videoUrlOrId, bool wantAuto, CancellationToken ct = default)
    {
        var url = Validate(videoUrlOrId);
        var dir = MakeTempDir();
        try
        {
            if (wantAuto)
            {
                var auto = await FetchAutoCuesAsync(url, dir, ct);
                return new SubtitleFetchResult(auto, IsAutoGenerated: true);
            }
            var manual = await FetchManualCuesAsync(url, dir, ct);
            if (manual is null || manual.Count == 0)
            {
                throw new SubtitleException("This video has no human-made (manual) subtitles.");
            }
            return new SubtitleFetchResult(manual, IsAutoGenerated: false);
        }
        finally
        {
            DeleteTempDir(dir);
        }
    }

    // 僅字幕、不下載影片；英文（含變體 en.*）；單片不展開清單。字幕格式逐趟指定（人工 VTT／自動 json3）。
    private const string CommonArgs = "--skip-download --sub-langs \"en.*\" --no-playlist";

    /// <summary>人工字幕趟（VTT）：查得回逐句 cue，無則回 null（無檔或無可讀句）。</summary>
    private async Task<IReadOnlyList<SubtitleCue>?> FetchManualCuesAsync(string url, string dir, CancellationToken ct)
    {
        var outTemplate = Path.Combine(dir, "sub");
        await RunYtDlpAsync($"{CommonArgs} --sub-format vtt --write-subs -o \"{outTemplate}\" \"{url}\"", _timeoutSec, "Fetching subtitles", ct);
        var manual = PickSub(dir, ".vtt");
        if (manual is null) { return null; }
        var cues = SubtitleParser.Parse(await File.ReadAllTextAsync(manual, ct));
        return cues.Count > 0 ? cues : null;
    }

    /// <summary>自動字幕趟（json3 事件級、乾淨無滾動；併句為 start-only）：查得回逐句 cue，無則擲 <see cref="SubtitleException"/>。</summary>
    private async Task<IReadOnlyList<SubtitleCue>> FetchAutoCuesAsync(string url, string dir, CancellationToken ct)
    {
        var outTemplate = Path.Combine(dir, "sub");
        var (exit, _, stderr) = await RunYtDlpAsync($"{CommonArgs} --sub-format json3 --write-auto-subs -o \"{outTemplate}\" \"{url}\"", _timeoutSec, "Fetching subtitles", ct);
        var auto = PickSub(dir, ".json3");
        if (auto is null)
        {
            throw new SubtitleException(exit != 0
                ? "Could not fetch subtitles: " + FirstMeaningfulLine(stderr)
                : "This video has no English subtitles available.");
        }
        // json3 事件級常過碎（單字 cue）→ 併為句級，讓到句暫停節奏順暢。
        var cues = SubtitleParser.CoalesceCues(SubtitleParser.ParseJson3Timed(await File.ReadAllTextAsync(auto, ct)));
        if (cues.Count == 0)
        {
            throw new SubtitleException("Subtitles were found but contained no readable lines.");
        }
        return cues;
    }

    private static string Validate(string videoUrlOrId)
    {
        if (string.IsNullOrWhiteSpace(videoUrlOrId))
        {
            throw new SubtitleException("Please paste a YouTube link or video ID.");
        }
        return videoUrlOrId.Trim();
    }

    private static string MakeTempDir()
    {
        var dir = Path.Combine(Path.GetTempPath(), "lingoisland-subs-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static void DeleteTempDir(string dir)
    {
        try { Directory.Delete(dir, recursive: true); } catch { /* best-effort temp cleanup */ }
    }

    /// <summary>
    /// 探測內嵌英文字幕可用性（#177）：以 <c>--print "%(subtitles)j"</c>／<c>"%(automatic_captions)j"</c> 只印 metadata（兩行 JSON），
    /// <b>不下載字幕、不下載影片</b>。以較短逾時避免整排結果卡住。取得失敗（私人／移除／逾時／yt-dlp 缺失）擲 <see cref="SubtitleException"/>。
    /// </summary>
    public async Task<EmbeddedSubtitleInfo> ProbeEmbeddedAsync(string videoUrlOrId, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(videoUrlOrId))
        {
            throw new SubtitleException("Please paste a YouTube link or video ID.");
        }
        var url = videoUrlOrId.Trim();
        // 兩個 --print 依序輸出兩行：行1＝subtitles（人工）、行2＝automatic_captions（自動）之 JSON 物件（鍵為語碼）。
        var args = $"--skip-download --no-warnings --no-playlist --print \"%(subtitles)j\" --print \"%(automatic_captions)j\" \"{url}\"";
        var (exit, stdout, stderr) = await RunYtDlpAsync(args, ProbeTimeoutSec, "Checking subtitles", ct);
        if (exit != 0 && stdout.Trim().Length == 0)
        {
            throw new SubtitleException("Could not check subtitles: " + FirstMeaningfulLine(stderr));
        }
        var lines = stdout.Replace("\r", "").Split('\n').Where(l => l.Trim().Length > 0).ToList();
        var subsJson = lines.Count > 0 ? lines[0] : "";
        var autoJson = lines.Count > 1 ? lines[1] : "";
        return ParseEmbeddedAvailability(subsJson, autoJson);
    }

    /// <summary>解析 yt-dlp <c>--print "%(subtitles)j"</c>／<c>"%(automatic_captions)j"</c> 兩段 JSON 物件為英文字幕可用性（#177）：任一鍵為英文語碼（en／en-US／en-GB／en-orig…）即視為有。非物件／空／malformed→false。internal 供單元測試。</summary>
    internal static EmbeddedSubtitleInfo ParseEmbeddedAvailability(string subtitlesJson, string autoCaptionsJson) =>
        new(HasEnglishKey(subtitlesJson), HasEnglishKey(autoCaptionsJson));

    /// <summary>JSON 物件是否含英文語碼鍵：<c>en</c> 或以 <c>en-</c>／<c>en.</c>／<c>en_</c> 起頭（涵蓋 en-US、en-GB、en-orig、a.en 等變體）。</summary>
    private static bool HasEnglishKey(string json)
    {
        if (string.IsNullOrWhiteSpace(json)) return false;
        try
        {
            using var doc = JsonDocument.Parse(json.Trim());
            if (doc.RootElement.ValueKind != JsonValueKind.Object) return false;
            foreach (var p in doc.RootElement.EnumerateObject())
            {
                var k = p.Name;
                if (k.StartsWith("en", StringComparison.OrdinalIgnoreCase)
                    && (k.Length == 2 || k[2] is '-' or '.' or '_'))
                {
                    return true;
                }
            }
            return false;
        }
        catch (JsonException) { return false; }
    }

    /// <summary>自暫存夾挑英文字幕檔（副檔名 <paramref name="ext"/>，如 <c>.vtt</c>／<c>.json3</c>）：優先精確 <c>.en{ext}</c>（自動字幕之翻譯版通常較 en-orig 乾淨）、次非 orig、末任一；無則 null。</summary>
    private static string? PickSub(string dir, string ext)
    {
        var files = Directory.EnumerateFiles(dir, "*" + ext).ToList();
        return files.FirstOrDefault(f => f.EndsWith(".en" + ext, StringComparison.OrdinalIgnoreCase))
            ?? files.FirstOrDefault(f => f.IndexOf("orig", StringComparison.OrdinalIgnoreCase) < 0)
            ?? files.FirstOrDefault();
    }

    /// <summary>清掉第一趟殘留的字幕檔（VTT／json3），避免第二趟 PickSub 誤挑到人工趟的檔。</summary>
    private static void ClearSubs(string dir)
    {
        foreach (var f in Directory.EnumerateFiles(dir).Where(
                     f => f.EndsWith(".vtt", StringComparison.OrdinalIgnoreCase)
                       || f.EndsWith(".json3", StringComparison.OrdinalIgnoreCase)).ToList())
        {
            try { File.Delete(f); } catch { /* best-effort */ }
        }
    }

    /// <summary>啟動 yt-dlp、回 (離開碼, stdout, stderr)；逾時或外部取消殺行程，逾時擲 <see cref="SubtitleException"/>（訊息含 <paramref name="timeoutWhat"/>），外部取消傳遞 <see cref="OperationCanceledException"/>。</summary>
    private async Task<(int exit, string stdout, string stderr)> RunYtDlpAsync(string args, int timeoutSec, string timeoutWhat, CancellationToken ct)
    {
        var psi = new ProcessStartInfo
        {
            FileName = _ytDlpPath,
            Arguments = args,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        Process? p;
        try
        {
            p = Process.Start(psi);
        }
        catch (Exception ex)
        {
            throw new SubtitleException(
                "yt-dlp could not be started (ensure yt-dlp is installed and on PATH): " + ex.Message);
        }
        if (p is null)
        {
            throw new SubtitleException("yt-dlp could not be started (ensure yt-dlp is installed and on PATH).");
        }

        using (p)
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            cts.CancelAfter(TimeSpan.FromSeconds(timeoutSec));
            var stdoutTask = p.StandardOutput.ReadToEndAsync(cts.Token);
            var stderrTask = p.StandardError.ReadToEndAsync(cts.Token);
            try
            {
                await p.WaitForExitAsync(cts.Token);
            }
            catch (OperationCanceledException)
            {
                try { p.Kill(entireProcessTree: true); } catch { /* ignore */ } // 逾時或外部取消皆殺行程、免孤兒 yt-dlp
                if (!ct.IsCancellationRequested)
                {
                    throw new SubtitleException($"{timeoutWhat} timed out ({timeoutSec}s).");
                }
                throw; // 外部取消（新 Load／取消鈕）→ 傳遞 OperationCanceledException，UI 顯示「Load canceled.」
            }
            var stdout = await stdoutTask;
            var stderr = await stderrTask;
            return (p.ExitCode, stdout, stderr);
        }
    }

    private static string FirstMeaningfulLine(string s)
    {
        var line = s.Split('\n').FirstOrDefault(l => l.Trim().Length > 0)?.Trim() ?? "unknown error";
        return line.Length > 200 ? line[..200] + "…" : line;
    }
}
