using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;
using LingoIsland.Video;
using Xunit;

namespace LingoIsland.Tests;

/// <summary>
/// 影片字幕存檔（<see cref="SubtitleStore"/>，#174；#189 資料夾式）：每支影片一資料夾（<c>{yyyyMMdd 標題}</c>）內含
/// subtitle.yaml＋info.json＋逐字稿 .txt；存讀往返、資料夾命名、逐字稿檔、刪除、清空、舊版扁平檔搬遷。
/// </summary>
public class SubtitleStoreTests
{
    private static string TempBase() => Path.Combine(Path.GetTempPath(), "li-vid-" + Guid.NewGuid().ToString("N"));
    private static void TryDelete(string dir) { try { if (Directory.Exists(dir)) { Directory.Delete(dir, true); } } catch { /* 清理盡力 */ } }
    private static SubtitleStore Store(string @base) => new(Path.Combine(@base, "video"));

    [Fact]
    public void SaveThenLoad_RoundTripsCuesFlagTitle()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            var cues = new List<SubtitleCue> { new("Hello there", 1.0, "Ryder"), new("Bark!", 2.5) };
            store.Save("abc123DEF-_", "Ready Race Rescue", isAutoGenerated: true, cues);
            var loaded = store.TryLoad("abc123DEF-_");
            Assert.NotNull(loaded);
            Assert.True(loaded!.IsAutoGenerated);
            Assert.Equal("Ready Race Rescue", loaded.Title);
            Assert.Equal(2, loaded.Cues.Count);
            Assert.Equal("Hello there", loaded.Cues[0].Text);
            Assert.Equal(1.0, loaded.Cues[0].StartSec);
            Assert.Equal("Ryder", loaded.Cues[0].Speaker); // 說話人隨字幕存回
            Assert.Null(loaded.Cues[1].Speaker);
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Save_CreatesFolderNamedByDateAndTitle()
    {
        var b = TempBase();
        try
        {
            Store(b).Save("vid", "Pups Save a School Day", false, new List<SubtitleCue> { new("x", 0.0) });
            var dirs = Directory.GetDirectories(Path.Combine(b, "video"));
            var name = Path.GetFileName(Assert.Single(dirs));
            Assert.Matches(@"^\d{8} Pups Save a School Day$", name);           // {yyyyMMdd} {title}
            Assert.True(File.Exists(Path.Combine(dirs[0], "subtitle.yaml")));
            Assert.True(File.Exists(Path.Combine(dirs[0], "info.json")));
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Save_SanitizesInvalidTitleChars()
    {
        var b = TempBase();
        try
        {
            Store(b).Save("vid", "A/B:C*D?\"E", false, new List<SubtitleCue> { new("x", 0.0) });
            var name = Path.GetFileName(Directory.GetDirectories(Path.Combine(b, "video"))[0]);
            foreach (var c in Path.GetInvalidFileNameChars()) { Assert.DoesNotContain(c, name); }
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void TryLoad_Missing_ReturnsNull()
    {
        var b = TempBase();
        try { Assert.Null(Store(b).TryLoad("nope")); }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Save_EmptyCues_NotPersisted()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            store.Save("vid", "T", false, new List<SubtitleCue>());
            Assert.Null(store.TryLoad("vid"));
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void SaveWebTranscript_WritesTxtInVideoFolder()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            store.Save("vid", "Ready Race Rescue", false, new List<SubtitleCue> { new("Hi", 0.0) });
            store.SaveWebTranscript("vid", "Ready Race Rescue", "Ryder: Hi\nChase: Ready!", "PAW Patrol Wiki (fandom)");
            var folder = Directory.GetDirectories(Path.Combine(b, "video"))[0];
            var txt = Directory.GetFiles(folder, "*.txt");
            var f = Assert.Single(txt);
            Assert.Matches(@"^\d{8} PAW Patrol Wiki .*\.txt$", Path.GetFileName(f)); // {yyyyMMdd} {source}.txt
            Assert.Equal("Ryder: Hi\nChase: Ready!", File.ReadAllText(f));
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Save_PreservesTranscriptTxt()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            store.Save("vid", "T", false, new List<SubtitleCue> { new("Hi", 0.0) });
            store.SaveWebTranscript("vid", "T", "Ryder: Hi", "src");
            // 之後覆寫 cue（再標說話人）不應動到逐字稿 .txt
            store.Save("vid", "T", false, new List<SubtitleCue> { new("Hi", 0.0, "Ryder"), new("Bark", 1.0) });
            var folder = Directory.GetDirectories(Path.Combine(b, "video"))[0];
            Assert.Single(Directory.GetFiles(folder, "*.txt"));                 // 逐字稿仍在
            Assert.Equal(2, store.TryLoad("vid")!.Cues.Count);                  // cue 已更新
            Assert.Equal("Ryder", store.TryLoad("vid")!.Cues[0].Speaker);
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Remove_DeletesFolder()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            store.Save("vid", "T", false, new List<SubtitleCue> { new("x", 0.0) });
            Assert.NotNull(store.TryLoad("vid"));
            store.Remove("vid");
            Assert.Null(store.TryLoad("vid"));
            Assert.Empty(Directory.GetDirectories(Path.Combine(b, "video")));
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void Clear_RemovesAll()
    {
        var b = TempBase();
        try
        {
            var store = Store(b);
            store.Save("a", "A", false, new List<SubtitleCue> { new("x", 0.0) });
            store.Save("bb", "B", false, new List<SubtitleCue> { new("y", 1.0) });
            store.Clear();
            Assert.Null(store.TryLoad("a"));
            Assert.Null(store.TryLoad("bb"));
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void MigrateLegacy_MovesFlatJsonToFolder()
    {
        var b = TempBase();
        try
        {
            // 造一份舊版扁平檔 subtitles\{id}.json（含 WebTranscript）
            var legacyDir = Path.Combine(b, "subtitles");
            Directory.CreateDirectory(legacyDir);
            var legacy = new
            {
                VideoId = "vid1",
                IsAutoGenerated = false,
                Cues = new[] { new { Text = "Hi", StartSec = 0.0, Speaker = "Ryder" } },
                SavedAt = "2026-07-15T10:00:00+08:00",
                WebTranscript = "Ryder: Hi",
                WebTranscriptSource = "Fandom",
            };
            File.WriteAllText(Path.Combine(legacyDir, "vid1.json"), JsonSerializer.Serialize(legacy));

            var store = Store(b);
            store.MigrateLegacy(new Dictionary<string, (string, string)>
            {
                ["vid1"] = ("Ready Race Rescue", "2026-07-14T09:00:00+08:00"),
            });

            // 舊檔已刪、新資料夾建立（日期取 AddedAt=2026-07-14）
            Assert.False(File.Exists(Path.Combine(legacyDir, "vid1.json")));
            var dirs = Directory.GetDirectories(Path.Combine(b, "video"));
            var name = Path.GetFileName(Assert.Single(dirs));
            Assert.Equal("20260714 Ready Race Rescue", name);
            Assert.True(File.Exists(Path.Combine(dirs[0], "subtitle.yaml")));
            Assert.Single(Directory.GetFiles(dirs[0], "*.txt")); // WebTranscript 搬成 .txt

            // 可正常載入
            var loaded = store.TryLoad("vid1");
            Assert.Equal("Ready Race Rescue", loaded!.Title);
            Assert.Equal("Ryder", loaded.Cues[0].Speaker);
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void TryLoad_FallsBackToLegacyFlatJson()
    {
        var b = TempBase();
        try
        {
            var legacyDir = Path.Combine(b, "subtitles");
            Directory.CreateDirectory(legacyDir);
            var legacy = new { VideoId = "vidX", IsAutoGenerated = true, Cues = new[] { new { Text = "Hi", StartSec = 0.0, Speaker = (string?)null } }, SavedAt = "" };
            File.WriteAllText(Path.Combine(legacyDir, "vidX.json"), JsonSerializer.Serialize(legacy));
            var loaded = Store(b).TryLoad("vidX"); // 尚未搬遷也能載入（不遺失）
            Assert.NotNull(loaded);
            Assert.True(loaded!.IsAutoGenerated);
            Assert.Equal("Hi", loaded.Cues[0].Text);
        }
        finally { TryDelete(b); }
    }

    [Fact]
    public void FolderFor_CreatesWhenMissing()
    {
        var b = TempBase();
        try
        {
            var path = Store(b).FolderFor("vid", "My Video");
            Assert.NotNull(path);
            Assert.True(Directory.Exists(path!));
            Assert.Matches(@"\d{8} My Video$", Path.GetFileName(path!));
        }
        finally { TryDelete(b); }
    }
}
